server:
  port: ${VERIFICATION_PORT:8082}

spring:
  application:
    name: ${APP_NAME:verification-service}

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

client:
  external:
    base-url: ${EXT_BASE_URL:http://localhost:9090}
    passport-path: ${EXT_PASSPORT_PATH:/ext/passport-check}
    inn-path: ${EXT_INN_PATH:/ext/inn-check}
    dl-path: ${EXT_DL_PATH:/ext/dl-check}
